SELECT TOP 10  * FROM TB_CG_OLIST_CUSTOMER

CREATE TABLE TB_ACT_OLIST_CUSTOMER
{
	
	CUSTOMER_ID NVARCHAR(150),
	CUSTOMER_UNIQUE_id NVARCHAR(150),
	CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
	CUSTOMER_CITY NVARCHAR(100),
	CUSTOMER_STATE CHAR(2)
}


INSERT INTO TB_ACT_OLIST_CUSTOMER
SELECT *  FROM TB_CG_OLIST_CUSTOMER


