SELECT TOP 10  * FROM TB_CG_PRODUCT_CATEGORY

CREATE TABLE TB_ACT_PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_NAME NVARCHAR(150),
    PRODUCT_CATEGORY_NAME_ENGLISH NVARCHAR(150)
	
	
);


INSERT INTO TB_ACT_PRODUCT_CATEGORY
SELECT * FROM TB_CG_PRODUCT_CATEGORY


UPDATE dbo.TB_ACT_OLIST_ORDERS SET [ORDER_ID] = null
where [ORDER_ID] = ''



select * from dbo.TB_ACT_OLIST_ORDERS

